#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LeakCanaryTest.Droid.Resource", IsApplication=true)]

namespace LeakCanaryTest.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::LeakCanaryTest.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::LeakCanaryTest.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::LeakCanaryTest.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::LeakCanaryTest.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::LeakCanaryTest.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::LeakCanaryTest.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::LeakCanaryTest.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::LeakCanaryTest.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::LeakCanaryTest.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::LeakCanaryTest.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::LeakCanaryTest.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::LeakCanaryTest.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::LeakCanaryTest.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::LeakCanaryTest.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::LeakCanaryTest.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::LeakCanaryTest.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::LeakCanaryTest.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::LeakCanaryTest.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::LeakCanaryTest.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::LeakCanaryTest.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::LeakCanaryTest.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxBind = global::LeakCanaryTest.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxDropDownItemTemplate = global::LeakCanaryTest.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxGroupItemTemplate = global::LeakCanaryTest.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxItemTemplate = global::LeakCanaryTest.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxLang = global::LeakCanaryTest.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxSource = global::LeakCanaryTest.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Droid.Support.Fragment.Resource.Attribute.MvxTemplate = global::LeakCanaryTest.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Id.MvvmCrossTagId = global::LeakCanaryTest.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Droid.Support.Fragment.Resource.Id.MvxBindingTagUnique = global::LeakCanaryTest.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Droid.Support.Fragment.Resource.String.library_name = global::LeakCanaryTest.Droid.Resource.String.library_name;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxBinding = global::LeakCanaryTest.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxBinding_MvxBind = global::LeakCanaryTest.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxBinding_MvxLang = global::LeakCanaryTest.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxControl = global::LeakCanaryTest.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxControl_MvxTemplate = global::LeakCanaryTest.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxExpandableListView = global::LeakCanaryTest.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::LeakCanaryTest.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxImageView = global::LeakCanaryTest.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxImageView_MvxSource = global::LeakCanaryTest.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxListView = global::LeakCanaryTest.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::LeakCanaryTest.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.Fragment.Resource.Styleable.MvxListView_MvxItemTemplate = global::LeakCanaryTest.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int MvxDropDownItemTemplate = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int MvxGroupItemTemplate = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int MvxLang = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int MvxTemplate = 2130771974;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030004
			public const int actualtabcontent = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int detail_fragment = 2130903045;
			
			// aapt resource value: 0x7F030000
			public const int DialogButton = 2130903040;
			
			// aapt resource value: 0x7F030006
			public const int list_fragment = 2130903046;
			
			// aapt resource value: 0x7F030001
			public const int LoadingText = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int MvvmCrossTagId = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int MvxBindingTagUnique = 2130903043;
			
			// aapt resource value: 0x7F030007
			public const int switchFragmentButton = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int testButton = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int the_notes = 2130903049;
			
			// aapt resource value: 0x7F03000B
			public const int titles_fragment = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int titles_fragment_holder = 2130903052;
			
			// aapt resource value: 0x7F03000A
			public const int title_line = 2130903050;
			
			// aapt resource value: 0x7F03000D
			public const int when_line = 2130903053;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Dialog_Names = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Fragment_Detail = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int Fragment_FirstHeader = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int Fragment_List = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int Fragment_SecondHeader = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int Fragment_Titles = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int ListItem_SimpleItem = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int Page_DetailView = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int Page_FormView = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int Page_HomeView = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int Page_TabView = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int Page_TitlesView = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int SplashScreen = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int tabs_1 = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int tabs_2 = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int tabs_3 = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int tabs_3_big = 2130968592;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int Icon = 2131034112;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int hello = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int library_name = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010000,0x7F010004 }
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771972};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			// aapt resource value: { 0x7F010006 }
			public static int[] MvxControl = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			// aapt resource value: { 0x7F010002 }
			public static int[] MvxExpandableListView = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			// aapt resource value: { 0x7F010005 }
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			// aapt resource value: { 0x7F010001,0x7F010003 }
			public static int[] MvxListView = new int[] {
					2130771969,
					2130771971};
			
			// aapt resource value: 0
			public const int MvxListView_MvxDropDownItemTemplate = 0;
			
			// aapt resource value: 1
			public const int MvxListView_MvxItemTemplate = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
